# Generated by Django 4.1.7 on 2023-03-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='tickets_list',
        ),
        migrations.AddField(
            model_name='bookings',
            name='tickets_number',
            field=models.IntegerField(default=1),
        ),
    ]
