# Generated by Django 4.1.7 on 2023-03-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_bookings_tickets_list_bookings_tickets_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='booking_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
