# Generated by Django 4.1.7 on 2023-03-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_tickets_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date_time',
            field=models.CharField(default='0000000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='passenger_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
