# Generated by Django 4.1.7 on 2023-03-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=255)),
                ('destination_city', models.CharField(max_length=255)),
                ('departure_quater', models.CharField(max_length=255)),
                ('destination_quater', models.CharField(max_length=255)),
                ('departure_date_time', models.CharField(max_length=255)),
                ('kilometer', models.IntegerField()),
            ],
        ),
    ]
